---
title: "Welcome"
output: 
  html_document:
    theme: flatly
    toc: true
    toc_float: true
---
# Welcome

Welcome everyone to this R Course for the Department of Linguistics at the University of Manchester. The course will be delivered by Paul Stott, based on material developed by Professor Andrew Stewart at the University of Manchester. 

There is a little bit of preparation work to do in advance. Before the course itself I'd like you to watch the videos below from Andrew and install R and RStudio Desktop. R is the programming language, and RStudio Desktop is the interface we use to interact with the language. It's important that you have working installations of R and RStudio Desktop on your computers before the course starts, so if you have any trouble getting those two things up and running please let me know in advance. You can contact me via [email](mailto:paul.stott-2@postgrad.manchester.ac.uk).

First off, have a look at these videos about the importance of Open Research with respect to research reptoducibility and transparency.

## Open Research (A Brief History)

First I'd like you to watch the following video where I describe the history of the replication crisis and the issues which have motivated a move towards the adoption of open and reproducible research practices. I cover the so-called replication crisis in the biomedical sciences, issues around open research, and summarise some of the initiatives (including the [UK Reproducibility Network](https://www.bristol.ac.uk/psychology/research/ukrn/)) that have been established to address the fundamental problems around open research, transparency, and reproducibility in science.


&nbsp;&nbsp;

<center>

<iframe width="560" height="315" src="https://youtube.com/embed/wJlonh-XALE" frameborder="0" data-external="1" allowfullscreen></iframe>

</center>

&nbsp;&nbsp;

## How to do Reproducible Research

One of the biggest challenges facing researchers who are used to the **old** way of conducting research is that they feel that they don't have the knowledge or technical skills to adopt open and reproducible research practices.  But it's not that hard!  Before you run your experiment, you can pre-register your hypotheses so that when you come to analyse and write-up your results, you can demonstrate that your predictions really were made in advance of data collection. You can also make your research data open (and FAIR) alongside your code so that others can recreate your analyses. And by posting your research article on a pre-print server (such as [PsyArXiv](https://psyarxiv.com) or [bioRxiv](https://www.biorxiv.org)) before submission to a journal, you make your research findings available to all. The adoption of open source software such as R, also means that any research findings you produce can be *re*-produced by others who can access your data and code. This principle of using open tools to allow us to produce open (and reusable) data and code is the fundamental philosophy behind all of the workshops in this unit. Have a look at the video below where I talk about how we can adopt open and reproducible research practices.

&nbsp;&nbsp;

<center>

<iframe width="560" height="315" src="https://youtube.com/embed/BscWSJFmsHE" frameborder="0" data-external="1" allowfullscreen></iframe>

</center>

&nbsp;&nbsp;

## Why R?

Both R and RStudio Desktop are examples of [Open Source Software](https://opensource.com/resources/what-open-source). Open Source is key to producing reproducible research as Open Source software is free and available to all.

In the video below, I'll introduce you to R and talk about the importance of adopting such tools in our research analysis workflows.

&nbsp;&nbsp;

<center>

<iframe width="560" height="315" src="https://youtube.com/embed/GKJmY_YebhU" frameborder="0" data-external="1" allowfullscreen></iframe>

</center>

&nbsp;&nbsp;

You can view the slides [here](https://docs.google.com/presentation/d/1CkatVluJFu_XoBo1iA0xfACc-V9v-_-DqV3KIPZHgMU/edit?usp=sharing).

## Getting Started

Before the course, please install R (the language) and RStudio Desktop (the interface that helps us interact with R) - each is available for MacOS, Windows, and Linux. The Mac version of R can be installed from [here](https://www.stats.bris.ac.uk/R/bin/macosx/R-4.0.5.pkg) and the Windows version from [here](https://www.stats.bris.ac.uk/R/bin/windows/base/R-4.0.5-win.exe).

The Mac version of RStudio Desktop can be installed from [here](https://download1.rstudio.org/desktop/macos/RStudio-1.4.1106.dmg) and the Windows version from [here](https://download1.rstudio.org/desktop/windows/RStudio-1.4.1106.exe).

If you any problems with either of the above, you can select a different version of R to download from [here](https://www.stats.bris.ac.uk/R/) and a different version of RStudio Desktop from [here](https://www.rstudio.com/products/rstudio/download/).

If you are using a Chromebook, or have a tablet, or are having difficulties installing R and RStudio Desktop on your computer, you can use [RStudio Cloud](https://rstudio.cloud/) to run the RStudio environment in your browser. You'll need to sign up - there is a free plan available which allows you to use the RStudio Cloud for 15 hours per month. 

&nbsp;&nbsp;

<center>

<iframe width="560" height="315" src="https://youtube.com/embed/nsu2WQIeP5I" frameborder="0" data-external="1" allowfullscreen></iframe>

</center>

&nbsp;&nbsp;

## Customising RStudio Desktop
 
 &nbsp;&nbsp;

<center>

<iframe width="560" height="315" src="https://youtube.com/embed/fwonkj-hZYc" frameborder="0" data-external="1" allowfullscreen></iframe>

</center>

&nbsp;&nbsp;

## Keeping Things Organised

&nbsp;&nbsp;

<center>

<iframe width="560" height="315" src="https://youtube.com/embed/JslVB6Vfn0Q" frameborder="0" data-external="1" allowfullscreen></iframe>

</center>

&nbsp;&nbsp;

## Installing Packages

When you first instal R, you'll see it comes with only a small number of packages. Much of the data wrangling/visualisation/modeling that we'll be doing on this course requires the use of additional packages. In this video I'll show you how to install the ones that we'll need to use.

&nbsp;&nbsp;

<center>

<iframe width="560" height="315" src="https://youtube.com/embed/_bsHuptFB3s" frameborder="0" data-external="1" allowfullscreen></iframe>

</center>

&nbsp;&nbsp;

## On The Day

Both days will be run via Zoom. Make sure you install the [Zoom client](https://zoom.us/download) beforehand.

Paul will circulate the Zoom details beforehand.

## License

The source code for each of the lessons in this course is licensed under the [MIT license](https://opensource.org/licenses/MIT).